version: "3.8"
services:
  handle_close_friends_local:
    container_name: handle_close_friends_local
    privileged: true
    working_dir: /app
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
    env_file:
      - .env.local
    ports:
      - "5000:5000"